Fix build error
Removing the nitro plugin fixes the error:

error during build:
Error: Failed to start the Vite preview server for prerendering
    at startPreviewServer

Solution told to me by Manuel Schiller on Discord. Some issue with nitro tanstack integration that causes this right now.